# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32.xci
# IP: The module: 'coregen_clk_crossing_fifo32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: G:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32.xci
# IP: The module: 'coregen_clk_crossing_fifo32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk_crossing_fifo32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
