# 
# Synthesis run script generated by Vivado
# 

set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/fei/chester0536/kc705/fpga/kc705.cache/wt [current_project]
set_property parent.project_path G:/fei/chester0536/kc705/fpga/kc705.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/fei/chester0536/kc705/fpga/kc705.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xci
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_ooc.xdc]
set_property is_locked true [get_files G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir G:/fei/chester0536/kc705/fpga/kc705.runs/coregen_clk2M_crossing_fifo_synth_1 -new_name coregen_clk2M_crossing_fifo -ip [get_ips coregen_clk2M_crossing_fifo]]

if { $cached_ip eq {} } {

synth_design -top coregen_clk2M_crossing_fifo -part xc7k325tffg900-2 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix coregen_clk2M_crossing_fifo_ coregen_clk2M_crossing_fifo.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ coregen_clk2M_crossing_fifo_stub.v
 lappend ipCachedFiles coregen_clk2M_crossing_fifo_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ coregen_clk2M_crossing_fifo_stub.vhdl
 lappend ipCachedFiles coregen_clk2M_crossing_fifo_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ coregen_clk2M_crossing_fifo_sim_netlist.v
 lappend ipCachedFiles coregen_clk2M_crossing_fifo_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ coregen_clk2M_crossing_fifo_sim_netlist.vhdl
 lappend ipCachedFiles coregen_clk2M_crossing_fifo_sim_netlist.vhdl

 config_ip_cache -add -dcp coregen_clk2M_crossing_fifo.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips coregen_clk2M_crossing_fifo]
}

rename_ref -prefix_all coregen_clk2M_crossing_fifo_

write_checkpoint -force -noxdef coregen_clk2M_crossing_fifo.dcp

catch { report_utilization -file coregen_clk2M_crossing_fifo_utilization_synth.rpt -pb coregen_clk2M_crossing_fifo_utilization_synth.pb }

if { [catch {
  file copy -force G:/fei/chester0536/kc705/fpga/kc705.runs/coregen_clk2M_crossing_fifo_synth_1/coregen_clk2M_crossing_fifo.dcp G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force G:/fei/chester0536/kc705/fpga/kc705.runs/coregen_clk2M_crossing_fifo_synth_1/coregen_clk2M_crossing_fifo.dcp G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force G:/fei/chester0536/kc705/fpga/kc705.runs/coregen_clk2M_crossing_fifo_synth_1/coregen_clk2M_crossing_fifo_stub.v G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force G:/fei/chester0536/kc705/fpga/kc705.runs/coregen_clk2M_crossing_fifo_synth_1/coregen_clk2M_crossing_fifo_stub.vhdl G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force G:/fei/chester0536/kc705/fpga/kc705.runs/coregen_clk2M_crossing_fifo_synth_1/coregen_clk2M_crossing_fifo_sim_netlist.v G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force G:/fei/chester0536/kc705/fpga/kc705.runs/coregen_clk2M_crossing_fifo_synth_1/coregen_clk2M_crossing_fifo_sim_netlist.vhdl G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir G:/fei/chester0536/kc705/fpga/kc705.ip_user_files/ip/coregen_clk2M_crossing_fifo]} {
  catch { 
    file copy -force G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_stub.v G:/fei/chester0536/kc705/fpga/kc705.ip_user_files/ip/coregen_clk2M_crossing_fifo
  }
}

if {[file isdir G:/fei/chester0536/kc705/fpga/kc705.ip_user_files/ip/coregen_clk2M_crossing_fifo]} {
  catch { 
    file copy -force G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_stub.vhdl G:/fei/chester0536/kc705/fpga/kc705.ip_user_files/ip/coregen_clk2M_crossing_fifo
  }
}
