# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xci
# IP: The module: 'coregen_clk2M_crossing_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk2M_crossing_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk2M_crossing_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk2M_crossing_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xci
# IP: The module: 'coregen_clk2M_crossing_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk2M_crossing_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk2M_crossing_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_clk2M_crossing_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
