# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/fei/chester0536/kc705/fpga/IP_Core/mem1/coregen_user_mem8.xci
# IP: The module: 'coregen_user_mem8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/mem1/coregen_user_mem8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_user_mem8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: G:/fei/chester0536/kc705/fpga/IP_Core/mem1/coregen_user_mem8.xci
# IP: The module: 'coregen_user_mem8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/mem1/coregen_user_mem8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_user_mem8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
