# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/fei/chester0536/kc705/fpga/kc705.cache/wt [current_project]
set_property parent.project_path G:/fei/chester0536/kc705/fpga/kc705.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/fei/chester0536/kc705/fpga/kc705.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  G:/fei/chester0536/kc705/fpga/kc705.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/d_ff.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/data_selector.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/delay_ff.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/gen_simple_data.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/gen_user_clock.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/gen_user_command.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/rec_sample_data.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/recieve_adc_packet.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/regen_ctrl_sig.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/set_chip_addr.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/set_data.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/state_control.v
  G:/fei/chester0536/kc705/fpga/HDL/adc/CPS_ReadOut_TOP_stub.v
  G:/fei/chester0536/kc705/fpga/HDL/xillybus/verilog/src/xillydemo.v
  G:/fei/chester0536/kc705/fpga/HDL/xillybus/verilog/src/xillybus.v
  G:/fei/chester0536/kc705/fpga/HDL/xillybus/verilog/src/xillybus_core.v
  G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_8x.v
  G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_8x_pipe_clock.v
  G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_vivado_pipe_clock.v
  G:/fei/chester0536/kc705/fpga/HDL/user_module/tlu_handshake.v
}
read_ip -quiet G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048_ooc.xdc]
set_property is_locked true [get_files G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048.xci]

read_ip -quiet G:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk.xci
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk_board.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk_ooc.xdc]
set_property is_locked true [get_files G:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk.xci]

read_ip -quiet G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado.xci
set_property used_in_synthesis false [get_files -all g:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_vivado/example_design/xilinx_pcie_7x_ep_x8g1_KC705_REVC.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_vivado/example_design/xilinx_pcie_7x_ep_x8g1_KC705_REVC.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_vivado/source/pcie_k7_vivado-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_vivado/synth/pcie_k7_vivado_ooc.xdc]
set_property is_locked true [get_files G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado.xci]

read_ip -quiet G:/fei/chester0536/kc705/fpga/IP_Core/mem1/coregen_user_mem8.xci
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/mem1/coregen_user_mem8_ooc.xdc]
set_property is_locked true [get_files G:/fei/chester0536/kc705/fpga/IP_Core/mem1/coregen_user_mem8.xci]

read_ip -quiet G:/fei/chester0536/kc705/fpga/IP_Core/mem2/coregen_buffer_mem16.xci
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/mem2/coregen_buffer_mem16_ooc.xdc]
set_property is_locked true [get_files G:/fei/chester0536/kc705/fpga/IP_Core/mem2/coregen_buffer_mem16.xci]

read_ip -quiet G:/fei/chester0536/kc705/fpga/IP_Core/mem3/coregen_mem8_chipaddr.xci
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/mem3/coregen_mem8_chipaddr_ooc.xdc]
set_property is_locked true [get_files G:/fei/chester0536/kc705/fpga/IP_Core/mem3/coregen_mem8_chipaddr.xci]

read_ip -quiet G:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32.xci
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32_ooc.xdc]
set_property is_locked true [get_files G:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32.xci]

read_ip -quiet G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xci
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo_ooc.xdc]
set_property is_locked true [get_files G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xci]

set_property edif_extra_search_paths G:/fei/chester0536/kc705/fpga/HDL/xillybus/core [current_fileset]
read_edif G:/fei/chester0536/kc705/fpga/HDL/adc/CPS_ReadOut_TOP.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/xillydemo.xdc
set_property used_in_implementation false [get_files G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/xillydemo.xdc]

read_xdc G:/fei/chester0536/kc705/fpga/HDL/adc/CPS_ReadOut_TOP.xdc
set_property used_in_implementation false [get_files G:/fei/chester0536/kc705/fpga/HDL/adc/CPS_ReadOut_TOP.xdc]

read_xdc G:/fei/chester0536/kc705/fpga/kc705.xdc
set_property used_in_implementation false [get_files G:/fei/chester0536/kc705/fpga/kc705.xdc]


synth_design -top kc705 -part xc7k325tffg900-2


write_checkpoint -force -noxdef kc705.dcp

catch { report_utilization -file kc705_utilization_synth.rpt -pb kc705_utilization_synth.pb }
