#
# Vivado (TM) v2017.2 (64-bit)
#
# create_project.tcl: Tcl script for re-creating project 'kc705'
#
# Generated by Vivado on Mon Mar 19 11:49:25 +0800 2018
# IP Build 1909766 on Thu Jun 15 19:58:00 MDT 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "G:/fei/chester0536/kc705/fpga/kc705.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/d_ff.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/data_selector.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/delay_ff.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/gen_simple_data.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/gen_user_clock.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/gen_user_command.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/rec_sample_data.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/recieve_adc_packet.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/regen_ctrl_sig.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/set_chip_addr.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/set_data.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/state_control.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/adc/CPS_ReadOut_TOP.edf"
#    "G:/fei/chester0536/kc705/fpga/HDL/adc/CPS_ReadOut_TOP_stub.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/xillybus/verilog/src/xillydemo.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/xillybus/verilog/src/xillybus.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/xillybus/verilog/src/xillybus_core.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_8x.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_8x_pipe_clock.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_vivado_pipe_clock.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/tlu_handshake.v"
#    "G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048.xci"
#    "G:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk.xci"
#    "G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado.xci"
#    "G:/fei/chester0536/kc705/fpga/IP_Core/mem1/coregen_user_mem8.xci"
#    "G:/fei/chester0536/kc705/fpga/IP_Core/mem2/coregen_buffer_mem16.xci"
#    "G:/fei/chester0536/kc705/fpga/IP_Core/mem3/coregen_mem8_chipaddr.xci"
#    "G:/fei/chester0536/kc705/fpga/IP_Core/fifo1/coregen_clk_crossing_fifo32.xci"
#    "G:/fei/chester0536/kc705/fpga/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xci"
#    "G:/fei/chester0536/kc705/fpga/HDL/xillybus/vivado-essentials/xillydemo.xdc"
#    "G:/fei/chester0536/kc705/fpga/HDL/adc/CPS_ReadOut_TOP.xdc"
#    "G:/fei/chester0536/kc705/fpga/kc705.xdc"
#    "G:/fei/chester0536/kc705/fpga/HDL/user_module/tlu_testbench.v"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "create_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project kc705 ./kc705 -part xc7k325tffg900-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects kc705]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/kc705.cache/ip" -objects $obj
set_property -name "part" -value "xc7k325tffg900-2" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "DisplayOnly" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/kc705.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/d_ff.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/data_selector.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/delay_ff.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/gen_simple_data.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/gen_user_clock.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/gen_user_command.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/rec_sample_data.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/recieve_adc_packet.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/regen_ctrl_sig.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/set_chip_addr.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/set_data.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/state_control.v"]"\
 "[file normalize "$origin_dir/HDL/adc/CPS_ReadOut_TOP.edf"]"\
 "[file normalize "$origin_dir/HDL/adc/CPS_ReadOut_TOP_stub.v"]"\
 "[file normalize "$origin_dir/HDL/xillybus/verilog/src/xillydemo.v"]"\
 "[file normalize "$origin_dir/HDL/xillybus/verilog/src/xillybus.v"]"\
 "[file normalize "$origin_dir/HDL/xillybus/verilog/src/xillybus_core.v"]"\
 "[file normalize "$origin_dir/HDL/xillybus/vivado-essentials/pcie_k7_8x.v"]"\
 "[file normalize "$origin_dir/HDL/xillybus/vivado-essentials/pcie_k7_8x_pipe_clock.v"]"\
 "[file normalize "$origin_dir/HDL/xillybus/vivado-essentials/pcie_k7_vivado_pipe_clock.v"]"\
 "[file normalize "$origin_dir/HDL/user_module/tlu_handshake.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/HDL/adc/CPS_ReadOut_TOP.edf"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "EDIF" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "edif_extra_search_paths" -value "$proj_dir/HDL/xillybus/core" -objects $obj
set_property -name "top" -value "kc705" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/HDL/xillybus/vivado-essentials/fifo_8x2048/fifo_8x2048.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/IP_Core/clk1/coregen_sysclk.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/HDL/xillybus/vivado-essentials/pcie_k7_vivado/pcie_k7_vivado.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/IP_Core/mem1/coregen_user_mem8.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/IP_Core/mem2/coregen_buffer_mem16.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/IP_Core/mem3/coregen_mem8_chipaddr.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/IP_Core/fifo1/coregen_clk_crossing_fifo32.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/IP_Core/fifo2/coregen_clk2M_crossing_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/HDL/xillybus/vivado-essentials/xillydemo.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/HDL/xillybus/vivado-essentials/xillydemo.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/HDL/adc/CPS_ReadOut_TOP.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/HDL/adc/CPS_ReadOut_TOP.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/kc705.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/kc705.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/kc705.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/HDL/user_module/tlu_testbench.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "unknown" -objects $obj
set_property -name "xsim.simulate.runtime" -value "1000 ns" -objects $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2017} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2017" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7k325tffg900-2" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2017} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2017" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7k325tffg900-2" -objects $obj
set_property -name "steps.phys_opt_design.is_enabled" -value "1" -objects $obj
set_property -name "steps.post_route_phys_opt_design.is_enabled" -value "1" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:kc705"
