# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/fei/chester0536/kc705/fpga/IP_Core/mem3/coregen_mem8_chipaddr.xci
# IP: The module: 'coregen_mem8_chipaddr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/mem3/coregen_mem8_chipaddr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_mem8_chipaddr'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: G:/fei/chester0536/kc705/fpga/IP_Core/mem3/coregen_mem8_chipaddr.xci
# IP: The module: 'coregen_mem8_chipaddr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/mem3/coregen_mem8_chipaddr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_mem8_chipaddr'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
