# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk.xci
# IP: The module: 'coregen_sysclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: G:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk.xci
# IP: The module: 'coregen_sysclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: g:/fei/chester0536/kc705/fpga/IP_Core/clk1/coregen_sysclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coregen_sysclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
